### ISSUE TITLE
Suppress stacktraces for RejectException

### ISSUE THREAD

**Issue by diegosalvi** [davidmoten/subethasmtp#11]
RejectException exists only to be catched later and report the error with code and message.

For performance reasons stacktrace generations could be disabled using Exception constructor (exists from Java7):
```
protected Exception(String message, Throwable cause,
                        boolean enableSuppression,
                        boolean writableStackTrace) {
```

What do you think?
I could submit a really easy patch for this.

**Comment by davidmoten** [comment]
Yes, great
