### ISSUE TITLE
WARNING: An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by arrowwind** [davidmoten/subethasmtp#129]
I am using jdk11. 

It shows the following warning.

_WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.eclipse.angus.mail.util.SocketFetcher (file:/D:/Maven%20Rep/org/eclipse/angus/angus-mail/2.0.2/angus-mail-2.0.2.jar) to method sun.security.util.HostnameChecker.getInstance(byte)
WARNING: Please consider reporting this to the maintainers of org.eclipse.angus.mail.util.SocketFetcher
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release_

To fix it.
Please update the dependency package 'angus-mail'.  

<dependency>
    <groupId>org.eclipse.angus</groupId>
    <artifactId>angus-mail</artifactId>
    <version>2.0.3</version>
</dependency>

**Comment by davidmoten** [comment]
Thanks I'll have a look now

**Comment by davidmoten** [comment]
I've released [7.0.2](https://github.com/davidmoten/subethasmtp/releases/tag/7.0.2) to Maven Central that fixes this, thanks for the report and the fix!
