### ISSUE TITLE
Question about SMTPUTF8

### ISSUE THREAD

**Issue by mnmallea** [davidmoten/subethasmtp#132]
Hi,
I'm trying to receive emails that contains UTF8 characters in their `From` or `To` addresses like `eñe@example.org`.
I saw that subetha doesn't advertise to support `SMTPUF8` so I am assuming that it doesn't support it at least by default.
Is there a way to enable its support? Does it depends on how we parse the data input stream or does it depend on the sever itself?

**Comment by davidmoten** [comment]
thanks for the question. I'll have to get my head around that as an SMTP extension first. I've noticed that some SMTP servers support utf-8 characters in From, To addresses by default and others require the support to be turned on by a command. I tend towards the first. Do you have an opinion on that?

**Comment by davidmoten** [comment]
I just modified a unit test to use a To with `eñe` and the message handler did not call the `recipient` method with that value. This suggests that we don't support general UTF-8 in addresses. I'll have a look soon.

**Comment by davidmoten** [comment]
I've knocked up *always-on* support for SMTPUTF8. I wonder if should be configurable. Can you review the [PR](https://github.com/davidmoten/subethasmtp/pull/133)?

**Comment by davidmoten** [comment]
Release [7.1.1](https://github.com/davidmoten/subethasmtp/releases/tag/7.1.1) with SMTPUTF8 support, on Maven Central now.
