### ISSUE TITLE
Reforwarding an incoming email to another SMTP server on the fly

### ISSUE THREAD

**Issue by lifeanddeath** [davidmoten/subethasmtp#26]
Hi, I want to process an incoming email based on its subject, and then simply re forward the email to another SMTP server. If the check on the mail subject fails, I want to forward it to no where and simply drop the mail. Can we achieve such a logic with this SMTP server? 

```
SMTPServer server = SMTPServer //
 .port(PORT) //
 .messageHandler(
   (from, to, data) -> 
      System.out.println(
          "message from " + from 
          + " to " + to
          + ":\n" + new String(data, StandardCharsets.UTF_8)))
 .build();
 
server.start();
```

I think here if we place the other smtp server's IP address to TO parameter of messageHandler, it should be pretty much done or? Thanks in advance.

**Comment by davidmoten** [comment]
Hehe, nope not that simple!

```java
SMTPServer server = SMTPServer //
 .port(PORT) //
 .messageHandler(
   (from, to, data) -> 
      process(from, to, data)
 .build();
```
*subethasmtp* is an SMTP receiver and has no built in logic for sending SMTP mail. However, what happens in the `process(from, to, data)` method is completely up to you. The `data` item is a stream of bytes that represents the DATA block of an SMTP message. You can build a new mail using javax.mail and include the bytes of the DATA block in its data block. 

There is an example of building an SMTP message for sending in the unit test [BasicMessageHandlerFactoryTest.java](src/test/java/org/subethamail/smtp/server/BasicMessageHandlerFactoryTest.java). Good luck!

**Comment by lifeanddeath** [comment]
Thanks a lot!

**Comment by lifeanddeath** [comment]
Hi David, I'm so sorry for the follow up question but I have realized a crucial issue.

In my application, a client will connect to my smtp server and then the smtp server will re-forward the incoming email to another smtp server. I'm able to do this part, after your clear explanation(thanks a lot!). However, here is the problem. I should authenticate to this second smtp server using username password authentication and currently this info is hard coded for testing purposes. But, a client who will connect to my smtp server should be asked for a password and then I wanna use this password to authenticate to that another smtp server. Is this possible? As expected, we cant use/see the plain text password in any form. So how am I supposed to use this password somehow or fetch it to use it for further authentication.

**Comment by davidmoten** [comment]
subethasmtp lets you specify a `MessageHandlerFactory` and an `AuthenticationHandlerFactory`. The `MessageHandlerFactory` is used to create a `MessageHandler` when a session starts. The `AuthenticationHandlerFactory` is used to create an `AuthenticationHandler` when the AUTH command is processed. You can record the username and password used in the `AuthenticationHandler` (and always allow if you want). The `MessageHandlerFactory.create` method that you can implement is passed a `MessageContext` which you can pass through to the created `MessageHandler`. Inside the `MessageHandler` you can call `MessageContext.getAuthenticationHandler` and then access the username and password used.  Job done.
