### ISSUE TITLE
Question: Is data() method in MessageHandler called only ONCE?

### ISSUE THREAD

**Issue by bcastellucci** [davidmoten/subethasmtp#27]
Greetings, just a quick question - is the data() method (in MessageHandler) called only once?

From what I can tell it is, but I just wanted to be sure I'm not missing something.

I need to make a decision at the end of the message and the done() method seemed perfect but then after looking at the code I realized by then my opportunity to return an error to the client is gone, so I moved one method back to data().

This seems like the right spot but again, just wanted to double check.

Thanks!

**Comment by davidmoten** [comment]
Yes, just once.

**Comment by bcastellucci** [comment]
Perfect. Thanks again!
