### ISSUE TITLE
How to make sure that enableTLS works correctly

### ISSUE THREAD

**Issue by lifeanddeath** [davidmoten/subethasmtp#29]
Hi, 

In my smtp server project, I want a client to be able to use startTLS command and with that he should be able to communicate over a secure channel using TLS. For this my set up looks like this 

`UsernamePasswordValidator usernamePasswordValidator = new AuthenticationValidator();
			EasyAuthenticationHandlerFactory authenticationHandlerFactory = new EasyAuthenticationHandlerFactory(
					usernamePasswordValidator);		SMTPServer.port(smtpPort).messageHandlerFactory(ersMailHandlerFactory).hideTLS(true).enableTLS().
					authenticationHandlerFactory(authenticationHandlerFactory).build().start();`

And client side sends an email using such a function:

`public  void sendEmail() {
		 // Add recipient
		 String to = "test@example.com";

		// Add sender
		 String from = "myusername@gmail.com";
		 final String username = "q@risv3.local";
		 final String password = "q";

		String host = "localhost";

		Properties props = new Properties();
		 props.put("mail.smtp.auth", "true");
		 props.put("mail.smtp.starttls.enable", "true"); 
		 props.put("mail.smtp.ssl.trust", host);
		 props.put("mail.smtp.host", host);
		 props.put("mail.smtp.port", "25000");

		// Get the Session object
		 Session session = Session.getInstance(props,
		 new javax.mail.Authenticator() {
		 protected PasswordAuthentication getPasswordAuthentication() {
		 return new PasswordAuthentication(username, password);
		 }
		 });

		try {
		 // Create a default MimeMessage object
		 Message message = new MimeMessage(session);
		 
		 message.setFrom(new InternetAddress(from));
		 
		 message.setRecipients(Message.RecipientType.TO,
		 InternetAddress.parse(to));
		 
		 // Set Subject
		 message.setSubject("Hi JAXenter");
		 
		 // Put the content of your message
		 message.setText("Hi there,we are just experimenting with JavaMail here");

		// Send message
		 Transport.send(message);

		System.out.println("Sent message successfully....");

		} catch (MessagingException e) {
		 throw new RuntimeException(e);
		 }
		 }`

So my problem is that I want to make sure that if startTLS is enabled on the client side, the smtp server should be able to support it. And if i run the smtp server(Shown above) it works all fine but I'm not sure if the communication is run through TLS, because as you can see I first hve to call **.hideTLS(true)** before enableTLS. and I'm not sure if this is correct way to do it. Importantly if i remove the hideTLS part and only call enableTLS on the smtp server, I get the following exception on the client side if i send an email to my smtp server:

`Exception in thread "main" java.lang.RuntimeException: javax.mail.MessagingException: Could not convert socket to TLS;
  nested exception is:
	javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at emailrelayserver.SendEmail.sendEmail(SendEmail.java:61)
	at emailrelayserver.EmailRelayServer.main(EmailRelayServer.java:20)
Caused by: javax.mail.MessagingException: Could not convert socket to TLS;
  nested exception is:
	javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at com.sun.mail.smtp.SMTPTransport.startTLS(SMTPTransport.java:1880)
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:648)
	at javax.mail.Service.connect(Service.java:317)
	at javax.mail.Service.connect(Service.java:176)
	at javax.mail.Service.connect(Service.java:125)
	at javax.mail.Transport.send0(Transport.java:194)
	at javax.mail.Transport.send(Transport.java:124)
	at emailrelayserver.SendEmail.sendEmail(SendEmail.java:56)
	... 1 more
Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:154)
	at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:2020)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1127)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379)
	at com.sun.mail.util.SocketFetcher.configureSSLSocket(SocketFetcher.java:507)
	at com.sun.mail.util.SocketFetcher.startTLS(SocketFetcher.java:447)
	at com.sun.mail.smtp.SMTPTransport.startTLS(SMTPTransport.java:1875)
	... 8 more
`

If someone can help me, I'd be more than happy and appreciate that a lot!

**Comment by davidmoten** [comment]
There is a full system integration unit test of startTls at https://github.com/davidmoten/subethasmtp/blob/master/src/test/java/org/subethamail/smtp/StartTLSFullTest.java, send method is in https://github.com/davidmoten/subethasmtp/blob/master/src/test/java/org/subethamail/smtp/TestUtil.java. Check that out.

**Comment by lifeanddeath** [comment]
Hey David, 

I truly appreciate you answer. 

However it doesn't click for me why we have to use **startTlsSocketFactory(sslContext)**  method. For example, I see that the server side and the client side uses the same keystore.jks and truststore files. Is it normal? Maybe it is my lack of expertise in the area but when I think logically, why simply calling the enableTLS(True) doesn't suffice ?

 Because in a real world application, I'll lay the smtp server application on some server and then it'll be listening for the connections. How am I supposed to ensure that they have the same keystore and truststore files for communication? 

I have the feeling that these are low level communications taking place in the network layers and just enableTLS should allow one to use starttls on the fly? Like I said I'm most likely missing the connection between components somewhere but if u'd break it down for me I'd be more than happy.! Thanks a lot! Greetings from germany

**Comment by davidmoten** [comment]
No, the client would have its own trust manager only, I think you're just seeing shortcuts for testing. So there's nothing much to do for the client, java platform will ensure a public/private key gets created on the fly for a session. However, if the public cert of the smtp server is not from an official authority then you have to add the public cert of the smtp server to the client's trust store for it to be accepted (I imagine there are in-code alternatives on this like accepting anything but its not advised for anything over the web). With regards to the SMTP server it's normal that private and public keys be specified and be constant just like for an HTTP server.

**Comment by lifeanddeath** [comment]
I see thanks for the clear explanation. 

To be honest, just to see if it works correctly, I used the exact same structure used in the testing code now. I created truststore and keystore .jks files using keytool. 

The problem is I'm keep getting the same error for some reason, can you please help troubleshooting me?

Here is the debug I keep getting from client side:

**

DEBUG SMTP: trying to connect to host "localhost", port 465, isSSL false
220 WIN-RIS3DEVAE1.localdomain ESMTP SubEthaSMTP null
DEBUG SMTP: connected to host "localhost", port: 465

EHLO WIN-RIS3DEVAE1.localdomain
250-WIN-RIS3DEVAE1.localdomain
250-8BITMIME
250-STARTTLS
250-CHUNKING
250 Ok
DEBUG SMTP: Found extension "8BITMIME", arg ""
DEBUG SMTP: Found extension "STARTTLS", arg ""
DEBUG SMTP: Found extension "CHUNKING", arg ""
DEBUG SMTP: Found extension "Ok", arg ""
STARTTLS
220 Ready to start TLS
Exception in thread "main" java.lang.RuntimeException: javax.mail.MessagingException: Could not convert socket to TLS;
  nested exception is:
	javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at emailrelayserver.SendEmail.sendEmail(SendEmail.java:79)
	at emailrelayserver.EmailRelayServer.main(EmailRelayServer.java:22)
Caused by: javax.mail.MessagingException: Could not convert socket to TLS;
  nested exception is:
	javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at com.sun.mail.smtp.SMTPTransport.startTLS(SMTPTransport.java:1880)
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:648)
	at javax.mail.Service.connect(Service.java:317)
	at javax.mail.Service.connect(Service.java:176)
	at javax.mail.Service.connect(Service.java:125)
	at javax.mail.Transport.send0(Transport.java:194)
	at javax.mail.Transport.send(Transport.java:124)
	at emailrelayserver.SendEmail.sendEmail(SendEmail.java:74)
	... 1 more
Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:154)
	at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:2020)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1127)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379)
	at com.sun.mail.util.SocketFetcher.configureSSLSocket(SocketFetcher.java:507)
	at com.sun.mail.util.SocketFetcher.startTLS(SocketFetcher.java:447)
	at com.sun.mail.smtp.SMTPTransport.startTLS(SMTPTransport.java:1875)
	... 8 more
**

In the beginning I thought it is probably because I didn't use any trust and key store jks files but I already created them and added to classpath in server side.  and on client side I'm using this against a possible CA problem.

**`		props.put("mail.smtp.ssl.trust", "*");
`**

**Comment by lifeanddeath** [comment]
Hi David, after some hustling, I was able to get it working. I'll leave it closed for now but i think i might have a follow up problem or a question. Then I'll reopen again. Thanks a lot for the help!!!

**Comment by lifeanddeath** [comment]
Hi David, after some hustling at least it seems to work somehow but I'm not sure if TLS is established before sending the email, the output looks like this  do you think its working correctly?
´
DEBUG SMTP: useEhlo true, useAuth true
DEBUG SMTP: useEhlo true, useAuth true
DEBUG SMTP: trying to connect to host "localhost", port 25000, isSSL false
220 WIN-RIS3DEVAE1.localdomain ESMTP SubEthaSMTP null
DEBUG SMTP: connected to host "localhost", port: 25000

EHLO WIN-RIS3DEVAE1.localdomain
250-WIN-RIS3DEVAE1.localdomain
250-8BITMIME
250-STARTTLS
250-CHUNKING
250 Ok
DEBUG SMTP: Found extension "8BITMIME", arg ""
DEBUG SMTP: Found extension "STARTTLS", arg ""
DEBUG SMTP: Found extension "CHUNKING", arg ""
DEBUG SMTP: Found extension "Ok", arg ""
STARTTLS
220 Ready to start TLS
EHLO WIN-RIS3DEVAE1.localdomain
250-WIN-RIS3DEVAE1.localdomain
250-8BITMIME
250-STARTTLS
250-CHUNKING
250-AUTH PLAIN LOGIN
250 Ok
DEBUG SMTP: Found extension "8BITMIME", arg ""
DEBUG SMTP: Found extension "STARTTLS", arg ""
DEBUG SMTP: Found extension "CHUNKING", arg ""
DEBUG SMTP: Found extension "AUTH", arg "PLAIN LOGIN"
DEBUG SMTP: Found extension "Ok", arg ""
DEBUG SMTP: Attempt to authenticate
DEBUG SMTP: check mechanisms: LOGIN PLAIN DIGEST-MD5 NTLM 
AUTH LOGIN
334 VXNlcm5hbWU6
cUByaXN2My5sb2NhbA==
334 UGFzc3dvcmQ6
cQ==
235 Authentication successful.
DEBUG SMTP: use8bit false
MAIL FROM:<myusername@gmail.com>
250 Ok
RCPT TO:<test@example.com>
250 Ok
DEBUG SMTP: Verified Addresses
DEBUG SMTP:   test@example.com
DATA
354 End data with <CR><LF>.<CR><LF>
From: myusername@gmail.com
To: test@example.com
Message-ID: <1867750575.0.1591966293245.JavaMail.Administrator@WIN-RIS3DEVAE1>
Subject: Hi JAXenter
MIME-Version: 1.0
Content-Type: text/plain; charset=us-ascii
Content-Transfer-Encoding: 7bit

Hi there,we are just experimenting with JavaMail here
.
250 Ok
QUIT
221 Bye
Sent message successfully....**

**Comment by davidmoten** [comment]
Just telnet to the server that you start up and follow the same command sequence. If when you do STARTTLS you get binary stuff back then TLS session has been initiated. That's how you confirm that TLS is really there.
