### ISSUE TITLE
DKIM validation

### ISSUE THREAD

**Issue by vellrya** [davidmoten/subethasmtp#77]
Hello, is there any example (or at least standalone java library) to perform sender validation by DKIM header?
I found a few example on Python, but without proper knowledge of DKIM specs I am afraid to make insecure implementation.

**Comment by davidmoten** [comment]
No I don't have an example. Specification is here https://datatracker.ietf.org/doc/html/rfc6376. I don't mind adding support to make this easier if you'd like to make a PR

**Comment by davidmoten** [comment]
What you can do is in your `MessageHandler` you take the data (the SMTP format bytes as an `InputStream`) and parse it using `jakarta.mail` artifact. Then there are libraries like [java-utils-mail-dkim](https://github.com/simple-java-mail/java-utils-mail-dkim) that help you with DKIM verification.

It doesn't make sense to me yet to include DKIM verification in this library but I'm prepared to reconsider if someone can provide a good case for it.

**Comment by ndvbd** [comment]
Also interested in DKIM, as it is a standard today, and a must for an SMTP server. If DKIM fails, email is spam.

**Comment by davidmoten** [comment]
Thanks. Have you tried DKIM verification using the mentioned library? It's possible all we need to have here is an example for people to use.

**Comment by ndvbd** [comment]
Hi, not yet.
