### ISSUE TITLE
Cut a non RC version for maven repo

### ISSUE THREAD

**Issue by duttonw** [davidmoten/subethasmtp#8]
Hi @davidmoten ,

I found your product after updating https://github.com/loopingz/aws-smtp-relay which used the original version.

I believe your version is in a better state and as no one has found/raised any issues since your last RC. Could you make it final and increment the version please.

Regards,

@duttonw

**Comment by davidmoten** [comment]
Sure I can release a non-RC, will be no different from the current latest version.

**Comment by davidmoten** [comment]
4.0.1 has been released to Maven Central
