### ISSUE TITLE
InputStream leaks on DeferredFileOutputStream

### ISSUE THREAD

**Issue by valenpo** [davidmoten/subethasmtp#84]
DeferredFileOutputStream.getInputStream() could return ByteArrayOutputStream or FileInputStream. 
Both cases it is good practice close stream on point it is init.

**Comment by davidmoten** [comment]
Thanks, I'll have a look.

**Comment by davidmoten** [comment]
PR #85 merged, I've deployed 6.0.3 to Maven Central with the fix, thanks @valenpo!
