### ISSUE TITLE
Replace dependency com.sun.mail:jakarta.mail by jakarta.mail:jakarta.mail-api

### ISSUE THREAD

**Issue by ghusta** [davidmoten/subethasmtp#89]
I saw _subethasmtp_ was upgraded to Jakarta Mail 2.0 in https://github.com/davidmoten/subethasmtp/pull/37.

Maybe the dependency _com.sun.mail:jakarta.mail_ could also be replaced by the more recent [jakarta.mail:jakarta.mail-api](https://mvnrepository.com/artifact/jakarta.mail), which is equivalent, and actively maintained ?

**Comment by ghusta** [comment]
⚠️  However it may **not be a good idea**, as classes in `com.sun.mail.*` are not present in _jakarta.mail-api_, but only in _jakarta.mail_...

See for example : 
- https://stackoverflow.com/questions/16807758/java-lang-noclassdeffounderror-com-sun-mail-util-maillogger-for-junit-test-case

**Comment by davidmoten** [comment]
ok, thanks for having a look at it. I don't see an advantage to including the mail api dep and an implementation for the moment. Happy to discuss further. I'll close the issue but feel free to reopen if there's more to say.

**Comment by ghusta** [comment]
Yes you're right, it's better to let it like this for the moment.
Thank you.
